/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_RED.h"
#include "LED_RED_aliases.h"
#include "LED_GREEN.h"
#include "LED_GREEN_aliases.h"
#include "LED_BLUE.h"
#include "LED_BLUE_aliases.h"
#include "I2CS.h"
#include "I2CS_I2C.h"
#include "I2CS_PINS.h"
#include "I2CS_I2C_PVT.h"
#include "I2CS_PVT.h"
#include "I2CS_BOOT.h"
#include "StripLights.h"
#include "StripLights_fonts.h"
#include "S0.h"
#include "S0_aliases.h"
#include "Button.h"
#include "Button_aliases.h"
#include "flex0.h"
#include "flex0_aliases.h"
#include "flex1.h"
#include "flex1_aliases.h"
#include "flex2.h"
#include "flex2_aliases.h"
#include "flex3.h"
#include "flex3_aliases.h"
#include "I2CS_SCBCLK.h"
#include "I2CS_sda.h"
#include "I2CS_sda_aliases.h"
#include "I2CS_scl.h"
#include "I2CS_scl_aliases.h"
#include "I2CS_SCB_IRQ.h"
#include "StripLights_HFCLK.h"
#include "StripLights_cisr.h"
#include "StripLights_fisr.h"
#include "StripLights_StringSel.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

